item {
    id: 1
    name: 'Mango'
}

item {
    id: 2
    name: 'Healthy'
}

item {
    id: 3
    name: 'Insufficient nutrients'
}

item {
    id: 4
    name: 'Sooty mold'
}

item {
    id: 5
    name: 'Foliar gall midge'
}